#!/usr/bin/php
<?php
/**
 * @file
 *   Executable script sldeploy
 *
 *
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 */

error_reporting(E_ALL);

require_once 'lib/sldeploy.class.php';
require_once 'lib/config_default.inc.php';

if (defined('PHP_MAJOR_VERSION') && PHP_MAJOR_VERSION>=5 && PHP_MINOR_VERSION>=3) {
  $paras = getopt('c::p:rvqjh');
}
else {
  $paras = getopt('p:rvqjh');
}



if (isset($paras['c'])) {
	$conf['config_file'] = $paras['c'];
  if (!file_exists($conf['config_file'])) {
    die('Can not read configuration file '. $conf['config_file'] ."\n");
  }
}
else if (file_exists('config.inc.php')) {
	$conf['config_file'] = chdir() .'/config.inc.php';
}
elseif (file_exists($_SERVER['HOME']. '/.sldeploy.inc.php')) {
	$conf['config_file'] = $_SERVER['HOME']. '/.sldeploy.inc.php';
}
elseif (file_exists('/etc/sldeploy.inc.php')) {
	$conf['config_file'] = '/etc/sldeploy.inc.php';
}
else {
	die("Configuration file config.inc.php missing!\n");
}

require $conf['config_file'];

// store command line parameters
$conf['paras'] = $paras;

$sldeploy = new sldeploy($conf);
exit($sldeploy->run());