#!/usr/bin/env php
<?php
/**
 * Executable script vcdeploy
 *
 * PHP version 5.3
 *
 * @category  Console
 * @package   Vcdeploy
 * @author    Alexander Meindl <a.meindl@alphanodes.com>
 * @copyright 2014 Alexander Meindl
 * @license   http://www.mozilla.org/MPL Mozilla Public License Version 1.1
 * @link      https://github.com/alexandermeindl/vcdeploy
 */

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('VCDEPLOY_COMPOSER_INSTALL', $file);
        break;
    }
}

unset($file);

if (!defined('VCDEPLOY_COMPOSER_INSTALL')) {
    echo 'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL;
    die(1);
}

require VCDEPLOY_COMPOSER_INSTALL;

error_reporting(E_ALL);


if (!defined('__DIR__')) {
    $ipos = strrpos(__FILE__, '/');
    define('__DIR__', substr(__FILE__, 0, $ipos) . '/');
    unset($ipos);
}

set_include_path(get_include_path() . PATH_SEPARATOR . __DIR__ . '/lib');

require 'vcdeploy/loader.class.php';
require 'vcdeploy/exception_handler.inc.php';

// load configuration
$conf = array();
require 'vcdeploy/config_default.inc.php';
require 'vcdeploy/load_config.php';

// set exception handler
$logger = Log::factory('file', $conf['log_file'], basename(__FILE__));
set_exception_handler('exceptionHandler');

$vcdeploy = new VcDeployLoader($conf);

exit($vcdeploy->parser());
